[package]
name = "cord-test-runtime-transaction-pool"
version = "0.9.2-dev"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.30"
parking_lot = "0.12.1"
thiserror = "1.0"
sc-transaction-pool = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sc-transaction-pool-api = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sp-blockchain = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sp-runtime = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
cord-test-runtime-client = { path = "../client" }
