[package]
name = "cord-test-client"
description = "Client testing utilities"
version = "0.9.2-dev"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = "6.1"
async-trait = "0.1.79"
codec = { package = "parity-scale-codec", version = "3.6.1" }
futures = "0.3.30"
serde = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
sc-client-api = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sc-client-db = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0", default-features = false, features = [
	"test-helpers",
] }
sc-consensus = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sc-executor = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sc-offchain = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sc-service = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0", default-features = false, features = [
	"test-helpers",
] }
sp-blockchain = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sp-consensus = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sp-core = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sp-keyring = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sp-keystore = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sp-runtime = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sp-state-machine = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
tokio = { version = "1.22.0", features = ["sync"] }
