[package]
name = "cord-cli-test-utils"
description = "CLI testing utilities"
version = "0.9.2-dev"
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
substrate-rpc-client = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sp-rpc = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
assert_cmd = "2.0.10"
nix = "0.26.2"
regex = "1.7.3"
tokio = { version = "1.22.0", features = ["full"] }
node-cli = { package = "cord-node-cli", path = "../../node/cli" }
node-primitives = { package = "cord-primitives", path = "../../primitives/cord" }
sc-cli = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
sc-service = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0" }
futures = "0.3.28"

[features]
try-runtime = ["node-cli/try-runtime"]
