[package]
name = "pallet-did-runtime-api"
description = "Runtime APIs for dealing with DIDs."
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# External dependencies
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.11.1", default-features = false, features = [
	"derive",
] }

# Internal dependencies
pallet-did = { default-features = false, path = '../../../pallets/did' }

# Substrate
sp-api = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0", default-features = false }
sp-std = { git = "https://github.com/dhiway/substrate-sdk", branch = "release-v1.10.0", default-features = false }
frame-system = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.10.0" }

[features]
default = ["std"]
std = [
	"frame-system/std",
	"codec/std",
	"sp-api/std",
	"sp-std/std",
	"scale-info/std",
	"pallet-did/std",
]
