[package]
name = 'pallet-did'
description = "Enables adding and removing decentralized identifiers (DIDs)."
authors = ['Dhiway <info@dhiway.com>', 'BOTLabs GmbH']
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dev-dependencies]
pallet-balances = { git = "https://github.com/dhiway/substrate-sdk", features = [
	"std",
], branch = "release-v1.10.0" }
frame-benchmarking = { git = "https://github.com/dhiway/substrate-sdk", features = [
	"std",
], branch = "release-v1.10.0" }
sp-keystore = { git = "https://github.com/dhiway/substrate-sdk", features = [
	"std",
], branch = "release-v1.10.0" }


[dependencies]
# External dependencies
log = "0.4.17"
fluent-uri = { version = "0.1.4", default-features = false }

# Internal dependencies
cord-utilities = { package = "cord-utilities", path = "../../utilities", default-features = false }
identifier = { package = "cord-identifier", path = "../../primitives/identifier", default-features = false }
pallet-chain-space = { package = "pallet-chain-space", default-features = false, path = '../chain-space' }

# Substrate dependencies
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
	"max-encoded-len",
] }
scale-info = { version = "2.11.1", default-features = false, features = [
	"derive",
] }
frame-support = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.10.0" }
frame-system = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.10.0" }
sp-core = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.10.0" }
sp-io = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.10.0" }
sp-runtime = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.10.0" }
sp-std = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.10.0" }

# Benchmarking dependencies
frame-benchmarking = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.10.0", optional = true }
pallet-balances = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.10.0", optional = true }
sp-keystore = { git = "https://github.com/dhiway/substrate-sdk", default-features = false, branch = "release-v1.10.0", optional = true }

[features]
default = ["std"]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"cord-utilities/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
]
std = [
	"codec/std",
	"pallet-chain-space/std",
	"identifier/std",
	"frame-support/std",
	"frame-system/std",
	"cord-utilities/std",
	"log/std",
	"pallet-balances/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-keystore/std",
	"sp-runtime/std",
	"sp-std/std",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"cord-utilities/try-runtime",
]
