name: srtool

on:
  push:
    branches:
      - develop
      - "release*"

jobs:
  wasm-release:
    runs-on: ubuntu-22.04

    env:
      CHAIN: "cord"
      RUNTIME_NAME: "cord-runtime"
      RUNTIME_DIR: "runtime"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Runner info
        run: |
          echo "Runner Storage:"
          df -h
          echo "Runner Memory:"
          cat /proc/meminfo

      - name: Srtool Build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.9.2
        with:
          chain: ${{ env.CHAIN }}
          runtime_dir: ${{ env.RUNTIME_DIR }}

      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > ${{ env.CHAIN }}-srtool-digest.json
          cat ${{ env.CHAIN }}-srtool-digest.json
          echo "Runtime location: ${{ steps.srtool_build.outputs.wasm }}"

      - name: Archive Runtime
        uses: actions/upload-artifact@v4.3.1
        with:
          name: ${{ env.CHAIN }}-runtime-${{ github.sha }}
          path: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ env.CHAIN }}-srtool-digest.json
